version: '3.4'

services:
  mssql:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123456
    ports:
      - "1433:1433"
  
  redis:
    ports:
      - "6379:6379"

  todolist.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mssql-server,1433;Database=TodoList;User=SA;Password=Admin123456
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  todolist.mvcclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=AdminQwerty123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - WebApiConfig__BaseUrl=http://webapi/api/
    ports:
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
