CREATE TABLE [User]
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(75) UNIQUE NOT NULL
);

CREATE TABLE Checklist
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(75) UNIQUE,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
);

CREATE TABLE Task
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	DueDate DATETIME2(7) NOT NULL,
	IsDone BIT NOT NULL,
	ParentId INT FOREIGN KEY REFERENCES Task(Id),
	ChecklistId INT FOREIGN KEY REFERENCES Checklist(Id) NOT NULL
);
