CREATE TABLE [Image]
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[Path] NVARCHAR(255) NOT NULL
);

CREATE TABLE Category
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(75) NOT NULL
);

CREATE TABLE [User]
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(125) UNIQUE NOT NULL
);

CREATE TABLE Checklist
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(75) UNIQUE,

	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
);

CREATE TABLE Task
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	StartDate DATETIME2 NOT NULL,
	DueDate DATETIME2,
	IsDone BIT NOT NULL,
	Geotag GEOGRAPHY,

	ParentId INT FOREIGN KEY REFERENCES Task(Id),
	CategoryId INT FOREIGN KEY REFERENCES Category(Id),
	ChecklistId INT FOREIGN KEY REFERENCES Checklist(Id) NOT NULL,
	ImageId INT FOREIGN KEY REFERENCES [Image](Id)
);
